apiVersion: v1
kind: Service
metadata:
  name:  helloworld-rtp-service
  namespace: helloworld
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000